version: "5"

services:
  app:
    image: openjdk:17.0.1-jdk-slim
    container_name: test_app
    working_dir: /app
    volumes:
      - ./app:/app
    command: ["java", "-jar", "app.jar"]
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/testdb
      SPRING_DATASOURCE_USERNAME: testuser
      SPRING_DATASOURCE_PASSWORD: testpassword
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: test_db
    restart: always
    environment:
      POSTGRES_DB: testdb
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpassword
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  db_data:
